### ISSUE TITLE
Data file not found

### ISSUE THREAD

**Issue by wrightaprilm** [courtneygrigsby/grigsbypythonpackage#1]
Hey Courtney,

The plethodon.phy file isn't included in the data directory here. Would you mind pushing the correct one? Let me know when you've done it and I'll update my local copy of the package and resume grading.

Thanks!

**Comment by cgrigs** [comment]
I apologize for the delay. I hadn't noticed the issue. 
I added a file with the correct format, to the 'data' folder of this package called "test-plethodon.phy"
Additionally, "ProjectThree.ipynb"  in this package contains the functions setup, and ready to be ran with the correct data.
